# Generated by Django 5.2.4 on 2025-07-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
                ('github_url', models.URLField()),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
