# Generated by Django 5.0.6 on 2025-07-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
