# Generated by Django 5.0.6 on 2025-07-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_project_image_project_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_name',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/img/'),
        ),
    ]
