services:
  - type: web
    name: jose-portafolio
    env: python
    rootDir: .
    buildCommand: bash backend/build.sh
    startCommand: gunicorn portafolio.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase: jose-db
      - key: ALLOWED_HOSTS
        value: joseportafolio.onrender.com
